### ISSUE TITLE
Can't add to RVM

### ISSUE THREAD

**Issue by jamieorc** [graalvm/truffleruby#120]
Following your instructions to add to RVM I get this error:

`Empty path passed to certificates update, functions stack: requirements_osx_update_openssl_cert_run rvm_requiremnts_fail_or_run_action __rvm_osx_ssl_certs_ensure_for_ruby __rvm_osx_ssl_certs_ensure_for_ruby_except_jruby external_mount external_mount_uniq main`

Looking for guidance.

**Comment by pitr-ch** [comment]
Thanks for reporting, I'll have a look. In the meantime you could try rbenv and chruby they work fine.

**Comment by pitr-ch** [comment]
3a18088c56bf875a7adc8f59a0c28a9d9358ac1c documents how to get RVM working until TruffleRuby supports openssl.
