### ISSUE TITLE
Known bugs in Ruby included with graalvm-0.22?

### ISSUE THREAD

**Issue by Confusion** [graalvm/truffleruby#137]
I previously installed graalvm-0.21, following your guides, and did some experiments with it. I installed bundler and some other gems and things ran fine.  Everything expected to work works, speed amazing!

Now I just downloaded graalvm-0.22, but I can't get bundler, or any other gem, to install. And I can't make sense of the reason: installing fails with
````
ERROR:  While executing gem ... (NoMethodError)
    undefined method `<<' for nil:NilClass
undefined method `<<' for nil:NilClass
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/request_set.rb:344:in `method_missing'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/request_set.rb:344:in `resolve'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/dependency_installer.rb:487:in `resolve_dependencies'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/commands/install_command.rb:239:in `install_gem'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/commands/install_command.rb:300:in `block in install_gems'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/commands/install_command.rb:296:in `each'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/commands/install_command.rb:296:in `install_gems'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/commands/install_command.rb:203:in `execute'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/command.rb:308:in `invoke_with_build_args'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/command_manager.rb:171:in `process_args'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/command_manager.rb:139:in `run'
/home/wever/bin/graalvm-0.22/language/ruby/lib/mri/rubygems/gem_runner.rb:55:in `run'
/home/wever/bin/graalvm-0.22/language/ruby/lib/bin/gem:21:in `<main>'
(core):1:in `load'
````

I did some debugging and at the start of the `resolve_dependencies` method, before the call to `request_set` on line `/lib/mri/rubygems/dependency_installer.rb:487`, the following happens:
````rinu 
    request_set = Gem::RequestSet.new
    puts "Initally request_set has @sets = #{request_set.sets}"
    request_set.development         = @development
    puts "After setting development, @sets = #{request_set.sets}"
    request_set.development_shallow = @dev_shallow
    puts "After setting development_shallow, @sets = #{request_set.sets}"
````
where the `puts` calls are mine. This outputs
````
Initally request_set has @sets = []
After setting development, @sets = false
After setting development_shallow, @sets = 
````
even though e.g. the `request_set.development=` method is, as far as I can tell, just the plain setter method generated by an `attr_accessor` declaration. I can see no reason why setting `development` should change the contents of the `@sets`instance variable of the RequestSet instance.

So I have to ask: are there perhaps known bugs in the Ruby implementation included with graalvm-0.22? Or am I doing something wrong?

**Comment by chrisseaton** [comment]
> are there perhaps known bugs in the Ruby implementation included with graalvm-0.22

Yes :) It's still a way off being finished in general.

**Comment by pitr-ch** [comment]
Yeah this is a known issue of Ruby included in GraalVM 0.22 release however it's already fixed for 23 which will be available in few weeks. Please wait a bit.

**Comment by Confusion** [comment]
Ok, no problem. Would I have known about this if I was subscribed to the dev mailinglist or is there some other way to keep up to date?

**Comment by chrisseaton** [comment]
We have a monthly release, usually around the 1st but delayed a bit this time.

This is a general mailing list for GraalVM that announces releases.

https://github.com/graalvm/truffleruby/blob/master/README.md#mailing-list

**Comment by Confusion** [comment]
Ok, I am now subscribed :)
