### ISSUE TITLE
cannot load such file -- openssl.so

### ISSUE THREAD

**Issue by etehtsea** [graalvm/truffleruby#17]
`macOS 10.12.2`
`graalvm-0.19-macosx-amd64-dk.tar.gz`

```
/tmp/graalvm-0.19-dk/bin/ruby -S gem install bundler
ERROR:  While executing gem ... (Gem::Exception)
    Unable to require openssl, install OpenSSL and rebuild ruby (preferred) or use non-HTTPS sources
```

```
/tmp/graalvm-0.19-dk/bin/ruby -ropenssl -e 'true'
/private/tmp/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require': cannot load such file -- openssl.so (LoadError)
	from /private/tmp/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /private/tmp/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/openssl/openssl.rb:13:in `<main>'
	from /private/tmp/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `gem_original_require'
	from /private/tmp/graalvm-0.19-dk/jre/language/ruby/lib/ruby/truffle/mri/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by chrisseaton** [comment]
Thanks for the report @etehtsea. We can't run OpenSSL or Nokogiri yet I'm afraid, so the error is correct.

https://github.com/graalvm/truffleruby#do-you-run-rails

Hopefully we will have these running in a couple of months.

**Comment by etehtsea** [comment]
@chrisseaton Oh, I missed that. I was confused because it failed with the same error even when I downloaded gem manually and tried install it through `gem install /tmp/bundler-<ver>.gem` It looks like `rubygems` always loads `openssl`.

**Comment by chrisseaton** [comment]
We do run parts of RubyGems and Bundler if you already have the gems locally. I don't know how to do it, @bjfish or @pitr-ch could we document it?

**Comment by chrisseaton** [comment]
Closing in favour of #61.
