### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by y8** [graalvm/truffleruby#2]
Hi. 

In the [State of the Union™](http://lists.ruby-lang.org/pipermail/jruby/2017-January/000511.html) letter you mentioned that:

> We are using the SubstrateVM, an ahead of time compiler for Java programs, to compile JRuby+Truffle to a single statically-linked binary, that doesn’t even have a dependency on a JVM

Could you please update README with system requirements, installation instructions and some kind of short progress report? As far I understand, it's still on the [Oracle Labs](http://www.oracle.com/technetwork/oracle-labs/program-languages/overview/index-2301583.html) under OTN license.

Also, it will be awesome to see answers to other obvious questions:

1. What's about TruffleRuby license? 
1. Do you have a roadmap? What is the current state? Short/mid/long term goals? How far away it is from begin "production-ready"?
1. Who are the "core team"? Where we can find them?
1. How development process will look like? Is there contribution guidelines? How it's build, tested and distributed? 

This is just from the top of my head. I bet others will have way more questions.

Thanks and congratulations!

**Comment by aemadrid** [comment]
+1

Although [1](http://lists.ruby-lang.org/pipermail/jruby/2017-January/000511.html) helps with some hints on the roadmap I could really use installation instructions. And license will be great too.

**Comment by chrisseaton** [comment]
Fixed by b9c4176. Let me know if that doesn't answer specific questions that you have.
