### ISSUE TITLE
Dependency on C extensions, contact channel?

### ISSUE THREAD

**Issue by bbozo** [graalvm/truffleruby#24]
Hi folks :) first of all, compliments on an amazing project, 2nd, a question. Where to ask questions? :) I opened up 2 SO tags for truffleruby and graalvm that you can use if you wish and to channel common Q&A regarding these projects:

1. https://stackoverflow.com/questions/tagged/truffleruby
2. https://stackoverflow.com/questions/tagged/graalvm

to ask the real question I was about to ask :) Why do you need libraries depending on C extensions, can't you use the JRuby world gems?

https://stackoverflow.com/questions/41779349/why-does-truffleruby-need-c-extensions

Kind regards

**Comment by chrisseaton** [comment]
That's for that question - I've answered it there, but I'll repeat here for the record.

> Running C extensions is hard because the C extension API is just the entire internals of MRI exposed as a header file. You aren't programming against a clean API - you're programming against all the implementation details and internal design decisions of MRI.
>
> JRuby's Java extensions have exactly the same problem! The JRuby Java extension API is just the entire internals of JRuby, and you aren't programming against an API, instead you're programming against all the implementations details and design decisions of JRuby.
>
> We plan to eventually tackle both problems in the same way - which is to add another level of abstraction over the C or Java code using an interpreter which we can intercept and redirect when required, so that it believes it is running against MRI or JRuby internals, but really we redirect these to our internals.
>
> We think C extensions are more important, so we're tackling those first. We haven't really started on Java extensions yet, but we have started the underlying interpreter for Java that we'll use.
>
> This video explains all
>
> https://youtu.be/YLtjkP9bD_U?t=1562

I'm watching both those StackOverflow tags now so I'll see other questions there.
