### ISSUE TITLE
Announce list?

### ISSUE THREAD

**Issue by kwerle** [graalvm/truffleruby#39]
jruby had a great announce email list in the early days.  I'd love to keep up to date with TruffleRuby in the same kinda way.

**Comment by chrisseaton** [comment]
There is the graalvm-dev list.

https://oss.oracle.com/mailman/listinfo/graalvm-dev

We haven't been posting much there, but we will start to do so. There is a once-monthly release of GraalVM, which is how we distribute TruffleRuby for end users.

**Comment by chrisseaton** [comment]
Fixed in bf6b97609180e64d0650075d372a3b0771fe2578
