### ISSUE TITLE
Usage with self-build graal-core

### ISSUE THREAD

**Issue by PragTob** [graalvm/truffleruby#5]
(this is sort of a continuation of the issues in jruby/jruby#4400 - I couldn't find a mailing list right away, if there is a more appropriate place, please let me know)

It's me again!

So I built `graal-core` with `mx` locally etc. now  I can't manage to get truffle/jt.rb to run with this.

I.e.:

```
tobi@speedy ~/github/rubykon $ GRAAL_HOME=~/github/graal-core/ ../truffleruby/tool/jt.rb run  --graal -e 'puts Truffle::Graal.graal?'
$ JAVACMD=/usr/lib/jvm/java-9-oracle/bin/java /home/tobi/github/truffleruby/bin/jruby -X+T -Xtruffle.core.load_path=/home/tobi/github/truffleruby/truffle/src/main/ruby -J-server -J-XX:+UnlockExperimentalVMOptions -J-XX:+EnableJVMCI -J-d64 -J--add-exports=java.base/jdk.internal.module=org.graalvm.compiler.graal_core -J--module-path=/home/tobi/github/truffle/mxbuild/modules/com.oracle.truffle.truffle_api.jar:/home/tobi/github/graal-core/mxbuild/modules/org.graalvm.compiler.graal_core.jar -e 'puts Truffle::Graal.graal?'
Exception in thread "main" java.util.ServiceConfigurationError: com.oracle.truffle.api.TruffleRuntimeAccess: org.graalvm.compiler.truffle.hotspot.HotSpotTruffleRuntimeAccess not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:536)
	at java.base/java.util.ServiceLoader.access$000(ServiceLoader.java:340)
	at java.base/java.util.ServiceLoader$ProviderImpl.<init>(ServiceLoader.java:630)
	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.next(ServiceLoader.java:987)
	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.next(ServiceLoader.java:895)
	at java.base/java.util.ServiceLoader$1.next(ServiceLoader.java:1160)
	at java.base/java.util.ServiceLoader$1.next(ServiceLoader.java:1152)
	at java.base/java.util.ServiceLoader$2.next(ServiceLoader.java:1257)
	at com.oracle.truffle.api.Truffle$1.run(Truffle.java:84)
	at com.oracle.truffle.api.Truffle$1.run(Truffle.java:61)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.oracle.truffle.api.Truffle.initRuntime(Truffle.java:61)
	at com.oracle.truffle.api.Truffle.<clinit>(Truffle.java:49)
	at com.oracle.truffle.api.impl.Accessor.<clinit>(Accessor.java:313)
	at com.oracle.truffle.api.vm.PolyglotEngine.<clinit>(PolyglotEngine.java:117)
	at org.jruby.truffle.Main.main(Main.java:102)
FAILED (pid 17122 exit 1): JAVACMD=/usr/lib/jvm/java-9-oracle/bin/java /home/tobi/github/truffleruby/bin/jruby -X+T -Xtruffle.core.load_path=/home/tobi/github/truffleruby/truffle/src/main/ruby -J-server -J-XX:+UnlockExperimentalVMOptions -J-XX:+EnableJVMCI -J-d64 -J--add-exports=java.base/jdk.internal.module=org.graalvm.compiler.graal_core -J--module-path=/home/tobi/github/truffle/mxbuild/modules/com.oracle.truffle.truffle_api.jar:/home/tobi/github/graal-core/mxbuild/modules/org.graalvm.compiler.graal_core.jar -e 'puts Truffle::Graal.graal?'
tobi@speedy ~/github/rubykon $ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

After trying a bunch of things I get the sinking feeling that it tries to run everything with my Java 9 EA (see the JAVACMD line it generates) although my default version is set to 8 and it seems that truffleruby doesn't work with Java 8 (well I thought it'd use Graal and it wouldn't matter, but I dunno how it all ties together). 

I tried forcing it to JDK 8 by setting JAVACMD/JAVA_HOME but it didn't quite work.

I get the sinking feeling that it might be because I built graal-core with Java 9 (to have that JVMCI enabled something version) and that this then forces JDK9 on execution but truffleruby doesn't work with that yet. Anyone to encourage/confirm/deny that working theory would be highly appreciated :)

truffleruby is at: 0dd1c17a07d777
graal-core is at:  3c054a05728f1e7 (I went back a couple of commits as the newest version requires a Java 9 EA version that isn't yet in the PPA I use)

Anyhow, any help would be appreciated as usual. :)

**Comment by eregon** [comment]
Yes, during the build process of graal-core, it remembers which Java was used (in `mx.graal-core/env`, as shown by adding `-v` to `mx` commands).
Graal-core also produces a different output if built with Java 9.
Java 9 + Graal is fairly hard to get right currently, as Jigsaw aka the module system in Java 9 is still evolving.

Your best bet is to build a fresh graal-core with labsjdk-8u111-jvmci-0.23 from [OTN](http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html)
or from https://github.com/dougxc/openjdk8-jvmci-builder/releases if you want the OpenJDK version.

We need to make this easier of course :)

**Comment by PragTob** [comment]
See, that's where my "just build this" anxiety comes from! ;P

Seriously though, thanks for the help :+1: I'll try that one of these evenings to finally get these benchmarks out there hopefully.

**Comment by eregon** [comment]
I've got a solution for it :smiley: 
Try `jt install graal-core` in latest truffleruby, that should do the job (Linux-only for now).

**Comment by PragTob** [comment]
Works great, thanks a bunch!!! :tada: 

You just saved me and probably others loads of time :green_heart: :heart: :purple_heart:

**Comment by PragTob** [comment]
The fix for now is Linux only, but as this was my initial issue and problem and it's solved now thanks to @eregon I'll close this out!

Thanks again! :dancer:
