### ISSUE TITLE
Is there a TruffleRuby logo?

### ISSUE THREAD

**Issue by ivoanjo** [graalvm/truffleruby#51]
Hello!

I know it's probably not very high on the priority list, but it would be great if truffleruby had a logo that could be used in presentations and on apps supporting it.

A followup question is: would you be interested in a community contribution for a logo? I'm not a designer but I believe I can convince one to help me :smile:

**Comment by chrisseaton** [comment]
There isn't a logo, no. It's not the sort of thing we have a budget for either.

If someone wanted to make a logo, and they gave it a very permissive licence, we could probably use it. I did a sketch myself a while ago but it's programmer-art I'm afraid.

![truffle-ruby](https://cloud.githubusercontent.com/assets/341094/22647574/41b95dae-ec6a-11e6-9dd4-bd142cef2760.png)

**Comment by ivoanjo** [comment]
I'll try to get the ball rolling then! :smile:

**Comment by y8** [comment]
Hey.

We'd like to contribute. So we've allocated some time of one of our [designers](https://github.com/heyheymasha) to this task.

We'll use this issue to "think out loud" so everyone can see the progress, directions and give feedback.

**Disclaimer: this is just work-in-progress report. All presented materials in this issue are just work-in-progres snapshots and they do not need any kind of "voting" or "approval" at the moment. But feel free to give a feedback!** 

If there will be something to choose from and maintainers will decide that public should vote, then we'll open a new issue for that.

**Comment by y8** [comment]
Our initial goal was "logo for truffleruby". We did a first sketching:

`1A-1`
![truffleruby 1a-1 15 feb 17](https://cloud.githubusercontent.com/assets/80930/23025591/bc03bc52-f45e-11e6-9cb7-017c40da82ae.png)


(I'm posting each image in separate comment so everyone can add their reactions)

**Comment by y8** [comment]
`1A-2`

![truffleruby 1a-2 15 feb 17](https://cloud.githubusercontent.com/assets/80930/23025643/f2216af0-f45e-11e6-9004-bbddf2abae15.png)

**Comment by y8** [comment]
`1B-1`

![truffleruby 1b-1 15 feb 17](https://cloud.githubusercontent.com/assets/80930/23025657/faea11b4-f45e-11e6-9e9a-61c97daf814f.png)

**Comment by y8** [comment]
`1C-1`

![truffleruby 1d-1 15 feb 17](https://cloud.githubusercontent.com/assets/80930/23025671/038423f0-f45f-11e6-9144-6c3015156b8a.png)

**Comment by y8** [comment]
`1D-1`

![truffleruby 1d-1 15 feb 17](https://cloud.githubusercontent.com/assets/80930/23025753/3d60de1a-f45f-11e6-8bd6-067cdedeb312.png)

**Comment by y8** [comment]
`1E-1`

![truffleruby 1e-1 15 feb 17](https://cloud.githubusercontent.com/assets/80930/23025767/48247b54-f45f-11e6-9858-170b2ab8b9f7.png)

**Comment by y8** [comment]
`1F-1`

![truffleruby 1f-1 15 feb 17](https://cloud.githubusercontent.com/assets/80930/23025779/53101690-f45f-11e6-9c4b-d8cca5cbc066.png)

**Comment by chrisseaton** [comment]
Wow those look great! I like the rays around the gem - that gives a unique look to the motif and conveys an idea of performance.

Let's leave them here for a while for any opinions, and to see what @ivoanjo wants to show us because I know his colleagues were working on something.

**Comment by y8** [comment]
After internal review it became clear that we are focusing too much on the "ruby" part and it's not quite working out. All ideas are rotating around pretty much the same concept. 

Clearly our goal was too abstract. So it's time to start asking the _right_ questions.

Let's start from obvious one:

### Why do we need a logo?

- **Identification**. There another ruby implementations around. We would like to help users to identify specific implementation. 
- **Trendy**! Others already have logos! 🤓 ([mri](https://www.ruby-lang.org/en/), [jruby](http://jruby.org), [rbx](https://rubinius.com)) Even vulnerabilities have logos and catchy names this days(ex.[heartbleed](http://heartbleed.com), see full [review](http://www.phirelight.com/branding-vulnerabilities/))

Basically, `truffleruby` is not the same thing as `mri` or `jruby`. So market is full of other brands, we need logo to compete with them.

**Comment by y8** [comment]
This leads us to next question:

### What makes `truffleruby` special?

Why do we think that `truffleruby` is match to the other competitors on the market? Thats a freebie! 

- **Truffle**. It's a secret sauce. New technology focused on making (fast) programming language design an easy and simple task (for programming language architects). 
- **Resources**. It's baked by guys with a big guns: Oracle with tremendous experience in this field. 

Hmm. So we were focusing on the `ruby` part, thinking about the gems and stuff, but in fact we need to focus on the `truffle` part. 

## Is there anything else made with truffle framework?

Yes, plenty:

- truffleruby
- fastr
- sulong (got a logo!)
- simplelanguage
- Graal.js

And all this languages are marketed around "truffle". So, yeah, we definitely need to focus on the `truffle` part.

**Comment by chrisseaton** [comment]
I did this general Truffle logo prototype years ago. It's not suitable for Ruby as there's nothing Ruby-specific about it, but it shows how the core innovation of Truffle (self-specialising AST interpreters) can make a theme.

![truffle-logo](https://cloud.githubusercontent.com/assets/341094/23027551/819a742c-f45c-11e6-9f68-9fbe13d27a62.png)

**Comment by y8** [comment]
### How this logo will be used?

Okay. Finally lets think about limitations or restrictions. Do we have any? Plenty:

- **Digitally**. It's a programming language: console-first. Then it's a web. But web is fragmented by screen dpi.
- **Unsupervised**. There no design team, so nobody to care about "correct usage".  Focus on making one single variant for all the sizes. So no "rasterish" variants (crossing off `1E-1`), logo should be vector one. And it should be easy to use!
- **Extendable**. It's whole bunch of the languages. Ideally, we need some kind "just-add-the-name-and-pick-a-colour" template. 
- **Publicly**. We need to publish sources and ready-to-use files with very permissive license (CC BY or CC0) and in the easy-to-modify file format (i.e. no Properitaty `ai` or `sketch` files). 

So, let's sum up and define new goal:

## Goal

We need a "Seal of Truffle". Strictly speaking:

- We need an extendable logo (umbrella branding) that will clearly show relation of the child brand (ie. `truffleruby` or `sulong`) to the parent brand **truffle**.

## Requirements:

- identifiable without child brand
- readable on different size ranges (lets say 32x32 and up) 
- do not contain "raster" features
- Ideally: accessible
- Ideally: easy to make new language logos

**Comment by chrisseaton** [comment]
I don't think we want to produce a global logo for Truffle though - that would be outside my responsibility and I don't know if those teams would pick up a logo from outside as we would.

**Comment by y8** [comment]
So, let's re-evaluate sketches in this iteration.

Definitely crossing off: 

- `1A-1`, `1A-2` and `1F-1` (without gem it just a letterwork)
- `1E-1` (too much small details)

Most likely crossing off:

- `1C-1` and `1B-1`. Without gem it's just another logo from the stock template.

What's left?

- `1D-1`

So, we've left with a marching piglet. Which is conceptually nice. Truffles are rare and pigs are used to find them. What's bad? To much details, gem is playing role in composition. But that can be improved.

What's next?

- Try to move piglet concept forward
- Since we left with only one concept: find at least 2 new concepts

When? 

- This iteration took about 15 hours (designer 12h, me 3h) from the scratch. So we'll settle on another 8h from designer and 2h from me. 
- According to the current schedule we can make it by end of the next week (Feb 24)

**Comment by y8** [comment]
> I don't think we want to produce a global logo for Truffle though - that would be outside my responsibility and I don't know if those teams would pick up a logo from outside as we would.

That's completely fine! It's better to have keep this in mind and give other teams an option of using the "family branding". This is pretty much the same amount of work on our side, so we can kill two birds with one stone.

But okay: If it will be too much to satisfy we'll drop this requirement.

**Comment by y8** [comment]
By the way, could you please tell a story how did you come up with a name? Are "merged" AST nodes from your prototype played a part? :)

**Comment by chrisseaton** [comment]
The name was I think either from @thomaswue or @woess. It referred to truffle as in the fungus, they tell me. Yes, we use a technique called 'partial evaluation' to take the nodes in your program and to fuse them and optimise them as one to produce the finished machine code.

**Comment by ivoanjo** [comment]
Woah, some competition, nice! Indeed, @talkdesk is also working on our own submission, I hope to have some designs to share too. May the best logo win :)

**Comment by ivoanjo** [comment]
Just as an update, we had a small setback which led to some delays, but @talkdesk is still alive and we're working on our own proposals too :smile:

**Comment by ivoanjo** [comment]
Hello! Here's @talkdesk's proposal for a TruffleRuby logo. The design team initially considered doing several logos, but when they arrived at this design we all it was THE ONE and thus we have only one proposal.

They also prepared a pdf presentation with the motivation and several variants, which I've embedded below. To add a bit more impact on the reveal (and suspense), you'll need to click on the pdf itself to see the logo :)

[![truffleruby-proposal-cover](https://cloud.githubusercontent.com/assets/2785847/23799515/b71dce00-05a0-11e7-950f-74d1b43d13f1.png)](https://github.com/graalvm/truffleruby/files/834218/TruffleRuby-proposal.pdf)

So, what do you think?

**Comment by chrisseaton** [comment]
@y8 are you still working on more ideas to submit? When you're ready to put forward one or two final proposals we could have a vote between all of them.

**Comment by y8** [comment]
Ah, sorry I've completely forgot to post here as well. Couple weeks ago we decided to shut down our company, so it's all up to @heyheymasha now. 

Let's see what she have to say.

**Comment by chrisseaton** [comment]
@heyheymasha do you still want to have one of two of those logos considered? And would you still be able to make them available as CC? I don't know if they are an asset of the dissolved company and so involved in some legal problem.

**Comment by y8** [comment]
Legal entity is not dissolved yet, we just shut down the operations. 

As a active CEO, I'd like to make it simple and fair:

Yopp Inc. grants @heyheymasha with all the rights on all sources, designs, sketches, ideas and all other creative materials related to the truffleruby logo, without any liability, limitations or fees. This materials are transferred as is, without any warranty from Yopp Inc.

It's @heyhemasha work, so she can do whatever she like! :)

I hope this helps!

**Comment by y8** [comment]
I don't know is she is going to confirm it here, but @heyheymasha just told me that she is not willing to participate. I'll asked to release the sources, in case if you needed it.

Since there nobody left to pick it up here, this is it for us. :)

Good luck to @talkdesk!

**Comment by chrisseaton** [comment]
Ok, thanks anyway!

I'll post @talkdesk's contribution directly to make it easier for passers by to see :)

<img width="392" alt="i43 pimgpsh_fullsize_distr" src="https://cloud.githubusercontent.com/assets/341094/23875570/e6ae1f60-0831-11e7-9ff6-842a1c31e8cf.png">

We only have one logo to choose from but does anyone have any comments? Are there any potential issues with it? Anyone not like it? I think it's excellent.

**Comment by rmosolgo** [comment]
It's very attractive! I wish it had some connection to Truffle core concepts (AST interpretation, incremental self-optimization, compatibility with other Truffle languages), but since I'm also limited to "programmer art", I can't make a concrete contribution 😆 . Some ways to visualize those concepts that I can think of: 

- Downward-facing tree shape (perhaps with merged nodes, as in the logo above, representing the structure of Truffle programs)
- Repeated visual elements with gradual change (eg, increasing opacity or saturation, representing the self-improving program)
- Visual variety (like the rainbow colors above, representing the ability of Truffle runtimes to interoperate)

Ok, I might try to cook up a design or two after all, just for the sake of brainstorming. In any case, I'll be trying to grab one of the resulting stickers!

**Comment by hemju** [comment]
I really like the logo. Especially the incorporation of The Ruby symbol. The only concern is that there is a lot going on. The most timeless designs are simple, yet elegant.

**Comment by chrisseaton** [comment]
@rmosolgo I think you're thinking like a programmer! That's how I approach my programmer-art designs. I think a clever nod to the underlying technology is good if you can make it work, but trying to squeeze about five years of novel research ideas into a pictorial representation may be too much!

@hemju It does shrink all the way down fairly well, but yes at that stage you might want to remove the dots as they look just like stuck pixels. An artist could probably hint this better than I.

<img width="16" alt="32" src="https://cloud.githubusercontent.com/assets/341094/23877487/77ca425a-083a-11e7-8fd8-b0b2ea47f949.png">

**Comment by pitr-ch** [comment]
The rocket logo is great! Thanks @ivoanjo @talkdesk a lot. Having a scaled-down version without the dots is good idea.

I like the colour combination but It also looks to me quite playful (might be only my perception). The TruffleRuby is not of that nature, it aims to be a solid/mature (and fast which is already nicely captured by the rocket) implementation of Ruby. Do you think that a different colour combination could reflect it? Only a colour change may not work with rest of the logo though, in that case it does not matter, this is a minor concern.

**Comment by ivoanjo** [comment]
Thanks everyone for the feedback. We're definitely open to further evolve the design, as the design is for the truffleruby project, not our company :)

I would suggest that maybe people could vote with reactions on comments that include changes that they support, so that we could identify the most popular changes (if any) and I could then go back to the design team with that feedback; otherwise I'm not sure we will be able to incorporate all of the suggestions made in this thread on the same design.

**Comment by bjfish** [comment]
Could we see a variant with less flat design? E.g. add a small shadow: https://dribbble.com/shots/3219083--Discover-Sticker-Giveaway

**Comment by chrisseaton** [comment]
I really like the two colours as well by the way - gives us a second colour to use in other things we design besides just shades of red.

Yes, you can't incorporate everyone's off-hand remarks into new designs. As you say maybe see what people upvote here and then use your judgement to present any modifications and then we can accept or not.

My primary concern was for anyone to raise any potential issues (such as too similar to other logos) and that hasn't happened.

**Comment by dandlh** [comment]
Thought I'd chip in..

![tr](https://cloud.githubusercontent.com/assets/26404997/23922846/5e5eac64-0904-11e7-933a-05b317e4316b.png)

**Comment by rmosolgo** [comment]
I did end up sketching out a few ideas based on the Truffle logo suggested above ... but then I saw it was just a prototype, so it doesn't make much sense to base other work on it 😆 

![ruby_ideas](https://cloud.githubusercontent.com/assets/2231765/23959093/8cea3258-097a-11e7-8122-96d188457a1f.png)

Looking forward to seeing where it lands, but I don't have anything else to add :)

**Comment by ylluminate** [comment]
The rocket is great. I learned a very hard lesson years ago: TL;DR: Logos are about capturing a feeling, not concepts.

So, onto the story.  Many years ago, I worked with a committee of people to design a logo for an organization.  The budget was insane and I ended up iterating through roughly 100 designs.  No one ever seemed happy; or very few at a time.  In the end, after months of work, I popped up a cheapo logo design app and grabbed the first few items that popped up in random generation and I submitted them. The very  first one, which was simply a stupid swoosh (seemingly modified Nike symbol) won everyone's hearts instantly.  The stupid ugly logo that didn't convey a single concept goal that I had is still in use to this day after a decade.

The rocket represents a feeling that TRuby is going for.  If we want to work on something my 2¢ are that the name is absolutely not indicative of the project.  Give it a new name and that will go much farther than debating over the slick logo.  The entire goal here, from a marketing perspective, is about the feelings you generate.  Note codename "Raptor" for the revamped Passenger and what that did for the project...  Now that's worth some thought!  But as for the logo, yeah, hands down that's a winner.

(NOTE: every time I hear TruffleRuby I think of fungus.  I can't stop the image of mushrooms growing on old decaying forrest matter or dead trees or a pig digging up actual truffles.  I truly have a terrible image whenever anyone mentions "truffle" in relation to Ruby...)

**Comment by hemju** [comment]
I agree with @ylluminate. The rocket is by far the best logo, it captures the essence of TruffleRuby.

Sadly, I have to agree with the name. I always picture a pig searching for truffles :( I understand that the underlying technologies etc. are really important to you, but as for everyone else TruffleRuby sounds *really* weird. And stuff like this really matters. E.g. JavaScript's V8 sounds cool. It sounds like an engine, it sounds fast. Please don't forget the marketing concepts. TRuby needs to be and look cool if you want a wider adoption.

Btw. thanks @talkdesk for the contribution.

**Comment by chrisseaton** [comment]
@ylluminate @hemju thanks for the thoughts but I don't think it's likely we'll reconsider the name. We did think about some names like 'GraalRuby' but decided 'Truffle' was already somewhat established and had recognition in the Ruby community, so we're sticking with it.

**Comment by ylluminate** [comment]
I understand @chrisseaton.  I have grappled with the nomenclature for some time.  I've thought about how on earth it might be possible to maintain the existent brand recognition, while revitalizing the name.  It is sad that the name just has such negative / odd connotations outside of the inner circle. <sigh>  I wonder if there is a middle ground somewhere that would facilitate a name change while preserving this establishment?  I (and others) still think it merits thought even though there appears to be marriage.

**Comment by hemju** [comment]
Btw. @chrisseaton I am a huge fan of the project and you guys are doing amazing work (as do the JRuby guys). My comment was only towards the name, not the project. And yes, positive and rememberable names are helpful for marketing.

**Comment by thomaswue** [comment]
Maybe we should hand out Truffle chocolate cookies at every TruffleRuby talk to create positive association ;). What do you think @chrisseaton?

**Comment by hemju** [comment]
@thomaswue awesome idea! Maybe I'll do this at the next Ruby Meetup

**Comment by eregon** [comment]
Closed by #101.

**Comment by dextertzu** [comment]
TruffleRuby is an awesome name. Don't change it please and keep up the great work.
