### ISSUE TITLE
TruffleRuby with Graal does not work with Java 9

### ISSUE THREAD

**Issue by chrisseaton** [graalvm/truffleruby#556]
We have instructions for using TruffleRuby and Graal with an older early-access build of Java 9.

https://github.com/graalvm/truffleruby/blob/master/doc/user/using-java9ea.md

These worked in June, but unfortunately some more things changed in later early-access builds and we haven't yet updated these instructions. These need to be updated for the final release now.

**Comment by brauliobo** [comment]
thanks @chrisseaton, installing openjdk9 now, waiting for new instructions to continue with truffleruby

**Comment by chrisseaton** [comment]
Oh, and I forgot the other issue is that NFI recently became required, and Sulong is basically required, and we never got those running on Java 9 EA at all.

**Comment by chrisseaton** [comment]
Fix in #577.

**Comment by chrisseaton** [comment]
That's not a perfect solution I'm afraid. We recommend using GraalVM and won't support anything else at the moment (beyond attempting to be helpful).

**Comment by brauliobo** [comment]
@chrisseaton maybe it should be documented why graalvm is prefered over standard JDKs

**Comment by chrisseaton** [comment]
The GraalVM is the way we package up everything and distribute it for end-users. If you want to use a standard JDK you need to build everything from scratch.

https://github.com/graalvm/truffleruby/blob/master/doc/user/using-graalvm.md

**Comment by brauliobo** [comment]
hmmm, so there isn't a make task or command to build everything?

**Comment by chrisseaton** [comment]
The `mx` tool builds TruffleRuby and its dependencies.

https://github.com/graalvm/truffleruby/blob/master/doc/contributor/workflow.md

https://github.com/graalvm/truffleruby/blob/master/doc/contributor/building-graal.md

**Comment by chrisseaton** [comment]
I'll keep this open while we fix some more issues with Java 9 - the first being that you can't compile with Java 9.

**Comment by chrisseaton** [comment]
I've further fixed things #584, so you can now compile and run with Java 9 with Graal enabled.

**Comment by sandys** [comment]
@chrisseaton you mention this in the java 9 documentation:

> It is also possible to run on Java 9, but we do not support this and at the moment we only document it for interest.

Is this status quo for the foreseeable future ? or is the graal team looking to move to java 9 (as a lot of us were hoping) shortly ?

**Comment by chrisseaton** [comment]
GraalVM is sticking with a custom Java 8 build that includes JVMCI, for the foreseeable future. I'm not responsible for that and there are many projects which need to co-ordinate beyond TruffleRuby to upgrade - that's why it's not trivial to do.

We can fix any issues that people encounter, but I can't see a way to provide a GraalVM Java 9 release at the moment - it's just not something that this team is responsible for.
