### ISSUE TITLE
Can't install modern gems via Bundler

### ISSUE THREAD

**Issue by mperham** [graalvm/truffleruby#64]
```ruby
source "https://rubygems.org"
gem 'rack', '>= 2'
```

`bundle` fails with this Gemfile due to Bundler thinking the runtime is 2.0.0p648.  I have no idea why it thinks that.

```
$ bundle -v
Bundler version 1.14.4
```

**Comment by mperham** [comment]
```
$ bundle
Fetching gem metadata from https://rubygems.org/..............
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    rack (>= 2) was resolved to 2.0.1, which depends on
      ruby (>= 2.2.2)

Could not find gem 'ruby (>= 2.2.2)', which is required by gem 'rack (>= 2)', in any of the sources.
```

**Comment by mperham** [comment]
Maybe due to an old Rubygems version being packaged with Truffle?

**Comment by mperham** [comment]
Such that this gemspec requirement fails:

https://github.com/rack/rack/blob/master/rack.gemspec#L29

**Comment by bjfish** [comment]
Hi @mperham ,

Please try the following guide regarding install gems: https://github.com/graalvm/truffleruby/blob/master/doc/user/installing-gems.md

**Comment by eregon** [comment]
I'll close this as we can run Bundler and we test it in CI.
I also tried this specific case and it works fine.
