### ISSUE TITLE
Donate?

### ISSUE THREAD

**Issue by ipepe** [graalvm/truffleruby#8]
Is there a way to donate or support this project somehow? I am worried that this project will die because of not enough financial support.

**Comment by chrisseaton** [comment]
TruffleRuby is a project of Oracle Labs, who pay multiple people to work on it full time so we're ok for funding but thanks very much.

If you'd like to contribute we accept pull requests and we can help you find a place to get started.

**Comment by ipepe** [comment]
I'm high-level programmer so I don't think I may be a use. But I know a bit of sysopsing so I thought about creating Dockerfile?

**Comment by chrisseaton** [comment]
I'm going to write a document on our packaging this week or next. That might provide a first step for this.

**Comment by chrisseaton** [comment]
Closing in favour of #59. We can talk about Docker again with a new issue specifically for that when we're ready.
