### ISSUE TITLE
Ruby on WASM

### ISSUE THREAD

**Issue by ylluminate** [graalvm/truffleruby#82]
With [WASM having been deemed stable](https://lists.w3.org/Archives/Public/public-webassembly/2017Feb/0002.html), are there any thoughts on TruffleRuby also going into the browser?

Opal clearly is and has been the de facto standard of this (we're using it with great results for quite some time now), and I'm sure it will remain such for some time to come, but I was curious if there were any thoughts floating around in this regard from you guys.  Or, perhaps even, if Oracle has considered throwing a dev or two behind Opal to push it forward in this cutting edge (and what will be the future) area...

**Comment by chrisseaton** [comment]
We did have our JavaScript implementation compiled to JavaScript in the past, but this was just an experiment.

It's not something we're likely to focus on any time soon, as our whole approach is focused on server environments.

**Comment by ylluminate** [comment]
I can understand that.  Isomorphic development is so powerful and unifying in a team that it's something that I wish the majority of Ruby devs wouldn't ignore.  The nightmare of isomorphic JS has become such a standard, yet we keep suffering through ignorance and seemingly "political" connections in the Ruby / Rails community that we can't shake it off and really get behind isomorphic Ruby properly. <sigh>

**Comment by chrisseaton** [comment]
The other thing is that I think most people intend to use WebAssembly by using some LLVM backend, but I haven't looked at that. This means any language with an LLVM frontend gets this for free.

We don't have an LLVM frontend for our AOT tool, so we'd have to write an entire WebAssembly backend ourselves.

**Comment by chrisseaton** [comment]
There is http://dl.acm.org/citation.cfm?doid=2816707.2816715
