### ISSUE TITLE
Leap seconds not supported

### ISSUE THREAD

**Issue by nirvdrum** [graalvm/truffleruby#824]
It looks like when we moved from joda-time to the JDK 8 date/time APIs, we lost support for leap seconds. As far as I can tell the JDK doesn't support them, so supporting them in TruffleRuby is going to be tricky.

**Comment by eregon** [comment]
Do you have an example? Or could you add a spec for it?

**Comment by nirvdrum** [comment]
MRI always allows a value of `60` for the seconds component, even if it's not a valid leap second. That's the easiest way to look at it. Admitting an actual leap second requires setting your timezone to one that supports leap seconds and picking a date that had leap seconds.

```
irb(main):033:0> ENV['TZ'] = 'UTC'
=> "UTC"
irb(main):034:0> Time.utc(2015,6,30,23,59,60)
=> 2015-07-01 00:00:00 UTC

irb(main):035:0> ENV['TZ'] = 'right/UTC'
=> "right/UTC"
irb(main):036:0> Time.utc(2015,6,30,23,59,60)
=> 2015-06-30 23:59:60 UTC

```
