### ISSUE TITLE
rvm integration?

### ISSUE THREAD

**Issue by jaydanielian** [graalvm/truffleruby#9]
I am assuming eventually that truffleRuby will be available via RVM. Any rough timeframe for when that might happen? 

Also, will it be possible to run bundler in truffleRuby? I run the Roda web micro framework for a JSON API (thus I don't need the full Rails support), but would love to be able to play around with it once RVM has a version of truffleRuby to download

**Comment by chrisseaton** [comment]
I am going to write a document this week or not that explains what we are thinking of for running in environments like Heroku and Travis that can open this discussion again.

**Comment by bbozo** [comment]
Bundler + RVM + Travis is probably the main requirement for community adoption :+1: for you guys, amazing project

**Comment by brodock** [comment]
@bbozo also a docker container can be helpful (with you manage to get truffle in docker, you can run your tests in GitLab CI).

**Comment by chrisseaton** [comment]
@ipepe also volunteered to do something with Docker. All these ideas are prevented by our current click-through distribution though. We're looking at it.

**Comment by ylluminate** [comment]
So re: the click-through distribution issue that you mentioned [back here](https://github.com/jruby/jruby/issues/3768#issuecomment-203564314): 
> ...
> _In the past we did have a tarball that included Graal and JRuby, so you got the whole thing transparently, but we've moved away from that because we want to provide JS and R in the same package, and those are closed source and require click-through licenses so we can't ship in a tarball._
> ...
> 

I've seen some options before that include manually agreeing during download. Can you share the links that need click-through here and then perhaps we can brainstorm with you on solution options?

**Comment by chrisseaton** [comment]
The current link is

http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/

The solution isn't getting around the click-through (it's our click-through, Oracle put it there), it's sorting out the internal work to distribute it without needing a click-through in the first place.

**Comment by brodock** [comment]
@chrisseaton thanks for the hard-work and all the effort put into this project. I understand how internal bureaucracy undermines fast effort to release more publicly. Do you see anything we (the community) can do to help or perhaps JRuby/MRI team in terms of publicly statements that could help you guys?

This is for sure one of the most important projects for the Ruby community and every company around the ecosystem for the upcoming years.

**Comment by ylluminate** [comment]
So in the past, Linux distros have handled this click-through issue rather handily as per shell interaction with Java proper. 

Anyone able to fill us in here on the way it's done presently in terms of the actual workflow? I don't see why we can't duplicate this process.

**Comment by chrisseaton** [comment]
As I say the click-through is intended to be there and there isn't intended to be a way to download without it. Please don't speculate about ways around it in this comment thread, and make sure that you are in compliance with the OTN licence if you are using GraalVM.

**Comment by ylluminate** [comment]
💧💧💧💧😭💧💧💧💧  You've officially broken our hearts.

**Comment by eregon** [comment]
FWIW, it is possible to build TruffleRuby + graal-core on Linux in an automated way and without a click-through as documented in [Building Graal](https://github.com/graalvm/truffleruby/blob/master/doc/contributor/building-graal.md).

On OS X, we would need to have the user install a Java 8u111 (the version needed by Graal). This seems hard to automate as long as there are no public OpenJDK builds of JDK 8 on OS X available.

**Comment by harbirg** [comment]
I was was hoping to see truffleruby listed under "rvm list known" along with mri ruby, jruby, etc. It agree with others it would help with adoption if it was readily available in rvm. For now, I had to create an oracle account in addition to clicking OTN licence to download and test truffleruby. Appreciate all the work you guys are doing!

**Comment by chrisseaton** [comment]
Yes we hope to fix this soon.

**Comment by chrisseaton** [comment]
Closing in favour of #59.

**Comment by ylluminate** [comment]
And you've [officially unbroken](https://github.com/jruby/jruby/issues/3768#issuecomment-279883124) our hearts! ❤️ 😍 😍 😍

For anyone interested, you might follow along more closely as per:
https://github.com/jruby/jruby/issues/3768#issuecomment-279880405

Note especially [the discussion on `OpenSSL` and `Sulong`](https://github.com/graalvm/truffleruby/issues/61)!

Fascinating!  Cannot wait to see how this comes together technically.

**Comment by ipepe** [comment]
Is there a chance for rbenv?

**Comment by pitr-ch** [comment]
@ipepe Yes, I'll be looking at multiple ruby managers.
